const C={
 shion:{name:'紫音（シオン）',breed:'ベンガル',ig:'aqua_marine.33333',profile:'人を惹きつけるカリスマホスト。クールな自信家で観察力も鋭く、相手を喜ばせるのが得意。',img:'images/shion_result.png',line:'俺を選ぶんじゃなくて、俺に選ばれてみる？',final:'……やっと俺を見つけたね。でも、見つけたのは君だけじゃない。俺も、君を見つけてた。',copy:'あなたが惹かれるのは、自信と余裕をまとった特別な人。誰にでも魅力的な彼だからこそ、「その中で自分が選ばれる」ことにドキッとするタイプかも。紫音なら、あなたを自然にエスコートしながら、いつの間にか彼の世界へ引き込んでくれそう。'},
 ciel:{name:'シエル',breed:'シャム',ig:'kirara_aiart',profile:'ミレーヌ帝国の第3王子。優しく穏やかな王子様だけど、実は頭のキレる策士。',img:'images/ciel_result.png',line:'君のこと、待ってたんだよ。ほら、隣に座って。',final:'会えて嬉しい。なんとなく、君が来てくれるんじゃないかと思ってたんだ。',copy:'あなたが求めているのは、優しさの中にちょっぴり刺激のある恋。穏やかで何でも受け止めてくれるシエルだけど、実は一枚上手。気づいたときには彼のペース――そんな恋があなたには似合いそう。'},
 louis:{name:'ルイ',breed:'ロシアンブルー',ig:'proto0_0aiart',profile:'いつも眠そうな無気力男子。普段は誰にも興味を示さないのに、好きな相手だけは特別。',img:'images/louis_result.png',line:'君なら、隣にいても疲れないかも。',final:'放っておいてほしいけど……君は別。',copy:'あなたにぴったりなのは、頑張らなくても一緒にいられる相手。言葉や愛情表現が多くなくても、ただ隣にいるだけで落ち着ける関係を大切にするタイプ。誰にも興味を示さないルイが、あなただけには少しずつ心を開いてくれそう。'},
 rei:{name:'蒼井 怜',breed:'ロシアンブルー',ig:'chiharu_aiart',profile:'クールだけど実は世話焼きなグラフィックデザイナー。好きな子にだけ、ふっと優しく笑う。',img:'images/rei_result.png',line:'帰したくないって言ったら…もう少し、ここにいてくれる？',final:'…君のことだけは、どうしても放っておけない。',copy:'あなたは、言葉より行動で愛情を見せてくれる人に弱いみたい。クールに見えて、困ったときにはいつの間にかそばにいる――そんな怜とは、気づけばお互いが欠かせない存在になっていきそう。'},
 kurosu:{name:'蒼月 黒須',breed:'化け猫（黒猫）',ig:'amamikazuhito',profile:'夜の街に潜む謎めいた化け猫で、都市を守る守護者。都市伝説と推理が好き。',img:'images/kurosu_result.png',line:'月よりお前の顔を見ていたい。それだけで今日が救われる。',final:'別に期待してなかったけど……お前でよかったって思ってる。',copy:'あなたが惹かれるのは、簡単には心の中を見せてくれないミステリアスな人。少しずつ距離を縮めて、自分だけが知っている彼の一面を見つける恋に弱いタイプかも。黒須との恋は、静かだけれど誰より深いものになりそう。'},
 elliott:{name:'エリオット',breed:'ターキッシュアンゴラ',ig:'izayoi.miya',profile:'知的で上品な完璧執事。穏やかな紳士だけど、好きな人の前では少しだけ不器用。',img:'images/elliott_result.png',line:'……もう少しだけ、私の隣にいてください。あなたと飲む紅茶は、いつもより美味しいので。',final:'あなたの前では、完璧な紳士でいられなくなる。それでも……私のそばにいてくださいますか？',copy:'あなたにぴったりなのは、優しく丁寧に大切にしてくれる人。小さな変化まで気づいてくれる完璧な紳士なのに、恋となると少し不器用。そんな自分にだけ見せる余裕のなさが、あなたの心をくすぐりそう。'},
 hizuki:{name:'緋月（ひづき）',breed:'ソマリ（ルディ）',ig:'sui_anthurium',profile:'距離感近めの、ちょい悪な人たらし。本命には一途で、追われると少し余裕をなくす。',img:'images/hizuki_result.png',line:'ねぇ、俺じゃダメ？……結構、本気なんだけど。',final:'やっと捕まえた。……今さら逃げられると思ってる？',copy:'あなたは、ちょっと危険でドキドキする恋に惹かれるタイプ。距離を詰めて翻弄してくる緋月との恋は、毎日が刺激的。でも本気になった途端、余裕をなくすのは彼の方かも――？追うだけじゃない恋の駆け引きを楽しめそう。'},
 saku:{name:'朔 -Saku-',breed:'アメリカンショートヘア（黒）',ig:'usakuma.ruruu',profile:'人懐っこく距離感近めな無自覚甘えん坊。相手に似合う服やアクセを選ぶのが得意。',img:'images/saku_result.png',line:'ねぇ……なんでそんな離れてんの？',final:'ねぇ……そんな顔されたら、もっと近づきたくなるんだけど。',copy:'あなたにぴったりなのは、一緒にいるだけで自然と笑顔になれる人。気づけば隣にいて、甘えたりちょっかいを出したり。そんな朔とは、友達みたいに楽しいのに、ふとした瞬間に恋人の顔を見せる関係になりそう。'},
 adam:{name:'アダム',breed:'ボンベイ（黒猫）',ig:'aoi_mahoroba_ai_art',profile:'冷静沈着でカリスマ性のある起業家。簡単には心を許さないけれど、大切な相手には深い愛情を注ぐ。',img:'images/adam_result.png',line:'欲しいものがあるなら言え。……君の願いは俺が叶える。',final:'俺の隣を空けておいた。……君で俺を癒してくれないか？',copy:'あなたが求めているのは、迷ったときに頼れる強さを持った人。普段は簡単に心を許さないアダムだからこそ、自分だけが彼の特別な場所に入れることに惹かれるみたい。守られるだけじゃない、深く強い愛になりそう。'},
 nagi:{name:'凪（Nagi）',breed:'白猫',ig:'cerezopolaris_anime',profile:'穏やかで自然体なフォトグラファー。好きな相手には少しいたずらっぽく、不意打ちの甘さを見せる。',img:'images/nagi_result.png',line:'そんなに見てたら、こっちも見たくなるけど。',final:'……食べる？ せっかくだから、一口目は君にあげる',copy:'あなたにぴったりなのは、近すぎず遠すぎず、心地よい距離で寄り添ってくれる人。穏やかな凪との恋は、何気ない毎日が少しずつ特別になっていくタイプ。そこに突然やってくる不意打ちの甘さに、何度もドキッとさせられそう。'}
};
const Q=[
 {q:'彼と過ごすなら、どんな時間がいちばん好き？',a:[['ちょっと特別なお店で、おしゃれして大人っぽいデート',{shion:3,adam:2,elliott:1}],['カフェや本屋を巡りながら、のんびりお散歩',{nagi:3,rei:2,ciel:1}],['おうちでゴロゴロ。何もしない時間も一緒に楽しむ',{louis:3,saku:2,nagi:1}],['夜の街へ。行き先を決めず、気の向くまま冒険',{kurosu:3,hizuki:2,louis:1}],['彼が考えてくれた、とっておきのプランにおまかせ',{ciel:3,elliott:2,shion:1}]]},
 {q:'恋人とは、どんな距離感でいたい？',a:[['くっついたり甘えたり。好きなら距離は近い方がいい',{saku:3,hizuki:2,nagi:1}],['普段はそれぞれ自由。でも二人のときは特別',{louis:3,kurosu:2,rei:1}],['無理に言葉にしなくても、穏やかに分かり合いたい',{nagi:3,elliott:2,ciel:1}],['彼にリードされて、ちょっと振り回されるのも好き',{adam:3,shion:2,rei:1}],['追ったり追われたり。恋の駆け引きも楽しみたい',{hizuki:3,ciel:2,shion:1}]]},
 {q:'ちょっと落ち込んだ日。彼にしてほしいのは？',a:[['無理に聞き出さず、何も言わずそばにいてほしい',{louis:3,kurosu:2,nagi:1}],['小さな変化に気づいて、さりげなく気遣ってほしい',{elliott:3,ciel:2,rei:1}],['「大丈夫、俺に任せて」って頼もしく支えてほしい',{adam:3,rei:2,shion:1}],['冗談を言ったりちょっかいを出したりして、笑わせてほしい',{saku:3,hizuki:2,ciel:1}],['普段は見せない優しさを、自分にだけ見せてほしい',{kurosu:3,shion:2,louis:1}]]},
 {q:'一番キュンとする彼の「意外な一面」は？',a:[['クールなのに、私のことだけは放っておけない',{rei:3,louis:2,kurosu:1}],['いつも余裕たっぷりなのに、私から迫ると急に余裕をなくす',{hizuki:3,nagi:2,elliott:1}],['甘えたりふざけたりしているのに、大事なときは頼りになる',{saku:3,ciel:2,rei:1}],['完璧な紳士に見えるのに、恋愛になるとちょっと不器用',{elliott:3,adam:2,nagi:1}],['みんなを惹きつける人なのに、最後に選ぶのは私だけ',{shion:3,adam:2,kurosu:1}]]}
];
let step=0,scores={};Object.keys(C).forEach(k=>scores[k]=0);const app=document.querySelector('#app');
function shell(x){app.innerHTML=`<div class='wrap'><div class='card'>${x}</div></div>`;scrollTo(0,0)}
function start(){step=0;Object.keys(scores).forEach(k=>scores[k]=0);shell(`<img class='cover' src='images/cover.png'><h1 class='title'>猫耳男子診断</h1><p class='sub'>あなたと相性ぴったりの猫耳男子は……？<br>5つの質問から運命の彼を見つけよう🐾</p><button class='btn' onclick='question()'>診断スタート ♡</button>`)}
function question(){let x=Q[step];shell(`<div class='progress'><div class='bar' style='width:${(step+1)/5*100}%'></div></div><div class='qnum'>QUESTION ${step+1} / 5</div><h2>${x.q}</h2>${x.a.map((v,i)=>`<button class='choice' onclick='pick(${i})'>${String.fromCharCode(65+i)}. ${v[0]}</button>`).join('')}`)}
function pick(i){let p=Q[step].a[i][1];Object.entries(p).forEach(([k,v])=>scores[k]+=v);step++;if(step<4)question();else q5()}
function q5(){let top=Object.keys(scores).sort((a,b)=>scores[b]-scores[a]||Math.random()-.5).slice(0,3);top=top.sort(()=>Math.random()-.5);shell(`<div class='progress'><div class='bar' style='width:100%'></div></div><div class='qnum'>QUESTION 5 / 5</div><h2>ここまでの回答から、あなたと相性がよさそうな3人からメッセージが届きました🐾💕<br><br>一番キュンとする言葉はどれ？</h2><div class='three'>${top.map((k,i)=>`<button class='choice' onclick="result('${k}')">${String.fromCharCode(65+i)}. 「${C[k].line}」</button>`).join('')}</div>`)}
function result(k){let c=C[k];let shortName=c.name.replace(/（.*?）| -.*-/g,'');let igUrl=`https://www.instagram.com/${c.ig}/`;shell(`<div class='qnum' style='text-align:center'>YOUR CAT BOY IS...</div><h1 class='name'>${c.name}</h1><div class='breed'>${c.breed}</div><img class='result-img' src='${c.img}' alt='${c.name}'><div class='quote'>「${c.final}」</div><div class='result-copy'><b>あなたと${shortName}の相性は…♡</b><br><br>${c.copy}</div><div class='result-copy'><b>${c.name}ってこんな彼 🐾</b><br><br>${c.profile}</div><div class='result-actions'><button class='btn retry' onclick='start()'>↻ もう一度診断する</button><a class='btn creator' href='${igUrl}' target='_blank' rel='noopener noreferrer'>♡ Character by @${c.ig}</a></div><div class='tiny'>みんなでつくる♡猫耳男子診断<br><span class='credit'>©イケメン創作所</span></div>`)}
start();
